name: Update CIDRs

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Download akamai
        run: php bin/console app:single akamai -vvv
      - name: Download alibaba
        if: '!cancelled()'
        run: php bin/console app:single alibaba -vvv
      - name: Download aws
        if: '!cancelled()'
        run: php bin/console app:single aws -vvv
      - name: Download azure
        if: '!cancelled()'
        run: php bin/console app:single azure -vvv
      - name: Download cloudflare
        if: '!cancelled()'
        run: php bin/console app:single cloudflare -vvv
      - name: Download gcp
        if: '!cancelled()'
        run: php bin/console app:single gcp -vvv
      - name: Download hetzner
        if: '!cancelled()'
        run: php bin/console app:single hetzner -vvv
      - name: Download ibm
        if: '!cancelled()'
        run: php bin/console app:single ibm -vvv
      - name: Download oracle
        if: '!cancelled()'
        run: php bin/console app:single oracle -vvv
      - name: Push updates
        if: '!cancelled()'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com";
            git config --global user.name "github-actions[bot]";
            git add data;
            git commit -m "Updated CIDRs on $(date -Iminutes)";
          else
            echo "no changes";
          fi
      - name: Push changes
        if: '!cancelled()'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
