name: Update CIDRs

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Update CIDRs
        run: php bin/console app:download -vvv
      - name: Push updates
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "action@github.com";
            git config --global user.name "Update Bot";
            git add data;
            git commit -m "Updated CIDRs on $(date -Iminutes)";
            git push;
          else
            echo "no changes";
          fi
